<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Version>1.0.0</Version>
        <AssemblyName>CosmeticsManager</AssemblyName>
        <Authors>mxyx-club</Authors>
        <LangVersion>preview</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <DebugType>embedded</DebugType>
        <Configurations>Debug;Release;</Configurations>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    </PropertyGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="AmongUs.GameLibs.Steam" Version="2023.11.28" />
        <PackageReference Include="BepInEx.AutoPlugin" Version="1.1.0" />
        <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.735" />
        <PackageReference Include="BepInEx.IL2CPP.MSBuild" Version="2.1.0-rc.1" />
        <PackageReference Include="Reactor" Version="2.3.1" />
    </ItemGroup>
</Project>
